# settings from project-open-data.github.io

#document settings
title: FITARA
desc: "DESCRIPTION"
url: http://gsa.github.io/fitara/

#global settings, no need to change these
root_url: http://gsa.github.io/fitara/
org_name: gsa
repo_name: fitara
branch: gh-pages

# default build settings for running locally, no need to edit
pymgemnts: true
exclude: ["script", "vendor", "Gemfile", "Gemfile.lock", "config.ru", "Procfile", "Rakefile", "readme.md"]
markdown: kramdown
relative_permalinks: false

gems:
  - jekyll-redirect-from


# original settings

permalink: pretty
markdown: rdiscount
highlighter: pygments
url: http://management.cio.gov

collections:
  - guidanceSections

sass:
    sass_dir: assets/_sass
